version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "1337:1337"
    volumes:
      - ./src:/django
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:1337"
    environment:
      - DB_HOST=db
      - DB_NAME=pc-django
      - DB_USER=pc
      - DB_PASS=supersafepw
    depends_on:
      - db
    networks:
      - default
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=pc-django
      - POSTGRES_USER=pc
      - POSTGRES_PASSWORD=supersafepw
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default

volumes:
  db: